### ISSUE TITLE
incorrect timestamp generation

### ISSUE THREAD

**Issue by workingDog** [StephenOTT/STIX-Faker#2]
A very useful tool, thanks.

I noticed that when I use "GET /api/bundle", for
"type" : "observed-data" in "objects" : [...]
sometimes the observable "type" : "process" gets generated with
"created": 902938087
not a correct timestamp such as
"created": "2019-02-19T10:34:18.383Z"

This error appear from time to time seemingly at random.

**Comment by StephenOTT** [comment]
@workingDog thanks for the report.  Will check it out.

to confirm, Is this every time for the `process`?

can you provide a json example that received? (could be something else in the response cause it)

**Comment by StephenOTT** [comment]
@workingDog I see the issue.  Patching shortly

**Comment by StephenOTT** [comment]
@workingDog okayt should be patched as part of the [0.5.2](https://github.com/StephenOTT/STIX-Faker/releases/tag/0.5.2) release.  

Issue was with the following line.  It was missing.  
https://github.com/StephenOTT/STIX-Java/blob/0.6.1/src/main/java/io/digitalstate/stix/coo/objects/ProcessCoo.java#L57

**Comment by StephenOTT** [comment]
Reopen if issue occurs again.  But I was not able to reproduce post-fix.

**Comment by StephenOTT** [comment]
See the 0.5.2 release as it has additional fixes https://github.com/StephenOTT/STIX-Faker/releases/tag/0.5.2

**Comment by StephenOTT** [comment]
@workingDog just want to double check: issue was resolved?

**Comment by workingDog** [comment]
Sorry for not replying earlier, yes the issue is resolved.
I tested my Scala library against the generated data, and all seems to work well.
Thanks again for this tool.

**Comment by StephenOTT** [comment]
great! 👍
