### ISSUE TITLE
Temporality/Causality Inconsistency

### ISSUE THREAD

**Issue by packet-rat** [StephenOTT/STIX-Faker#8]
Dates/Times generated have temporal/causality inconsistency:

For example generated "sightings" show `last_observed` timestamp before `first_observed` 
```
     "first_observed": "1997-03-10T00:00:00.000Z",
     "last_observed": "1977-05-29T00:00:00.000Z",
```

**Comment by StephenOTT** [comment]
Yes this was a known issue during the first iteration. Needs to be fixed in second round.  Is it causing issues in validation?

**Comment by packet-rat** [comment]
Not with static validation.  However, we are considering use of your tool for populating test data sets where temporal consistency is required for inferencing and reasoning validation.  In the meantime keep up the great work as your tool has already proven to be invaluable.

**Comment by StephenOTT** [comment]
@packet-rat give https://github.com/StephenOTT/STIX-Faker/releases/tag/0.7.0 a try.

This update introduces what i believe to be proper random dates with the requested fixes for Temporality/Causality inconsistencies.

Please close if it fixes it up!

**Comment by StephenOTT** [comment]
@packet-rat were you able to test it out?

**Comment by packet-rat** [comment]
Sorry -- I missed this update on April 15th (I was immersed with the tax man for a few days).  I'll have a look sometime this week.

Pat Maroney




On Apr 22, 2019, at 8:45 AM, Stephen Russett <notifications@github.com> wrote:

@packet-rat <https://github.com/packet-rat> were you able to test it out?

**Comment by StephenOTT** [comment]
reopen if its a issue, but i believe its fixed
